version: '2.1'

services:
  7dtd:
    build:
      context: .
    container_name: 7dtd
    image: 7dtd:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8081:8081"
      - "26900:26900/udp"
      - "26901:26901/udp"
      - "26902:26902/udp"
    volumes:
      - /srv/7dtd:/data
